version: "3.3"
services:
  react-front:
    stdin_open: true
    build: 
      context: .
    ports: 
      - "3000:3000"
    volumes:
      # - "nodemodule:/app/node_modules"
      - "./src:/app/src/"

# volumes:
  # nodemodule: